#include <mtd_tc.h>

/*
	1 clk = 1uS
	cc[0] top makes the period (MFRQ)
*/
static void init_tc0_deadtime_counter () {
	MCLK_REGS->MCLK_APBCMASK |= MCLK_APBCMASK_TC0 (1) | MCLK_APBCMASK_TC1 (1);

	GCLK_REGS->GCLK_PCHCTRL[TC0_GCLK_ID] =
		GCLK_PCHCTRL_WRTLOCK (0) |
		GCLK_PCHCTRL_GEN (8) | // 8MHz
		GCLK_PCHCTRL_CHEN (1);

	TC0_REGS->COUNT32.TC_CTRLA = TC_CTRLA_SWRST (1);
	while (TC0_REGS->COUNT32.TC_SYNCBUSY & TC_SYNCBUSY_SWRST (1));

	TC0_REGS->COUNT32.TC_CTRLA = 
		TC_CTRLA_COPEN0 (0) |
		TC_CTRLA_COPEN1 (0) |
		TC_CTRLA_CAPTEN0 (0) |
		TC_CTRLA_CAPTEN1 (0) |
		TC_CTRLA_ALOCK (0) |
		TC_CTRLA_PRESCALER_DIV8 |
		TC_CTRLA_ONDEMAND (0) |
		TC_CTRLA_RUNSTDBY (0) |
		TC_CTRLA_PRESCSYNC_GCLK |
		TC_CTRLA_MODE_COUNT32 |
		TC_CTRLA_ENABLE (0);
	TC0_REGS->COUNT32.TC_CTRLBSET = TC_CTRLBSET_ONESHOT (1);
	TC0_REGS->COUNT32.TC_EVCTRL =
		TC_EVCTRL_MCEO0 (0) |
		TC_EVCTRL_MCEO1 (1) |
		TC_EVCTRL_OVFEO (1) |
		TC_EVCTRL_TCEI (0) |
		TC_EVCTRL_TCINV (0) |
		TC_EVCTRL_EVACT_OFF;
	TC0_REGS->COUNT32.TC_WAVE = TC_WAVE_WAVEGEN_MPWM;
	TC0_REGS->COUNT32.TC_CC[0] = TC_COUNT32_CC_CC (0);
	TC0_REGS->COUNT32.TC_CCBUF[0] = TC_COUNT32_CCBUF_CCBUF (0);
	TC0_REGS->COUNT32.TC_INTENSET = TC_INTENSET_OVF (1);

	TC0_REGS->COUNT32.TC_CTRLA |= TC_CTRLA_ENABLE (1);
}

static void init_tc4_fan_pwm () {
	MCLK_REGS->MCLK_APBCMASK |= MCLK_APBCMASK_TC4 (1);

	GCLK_REGS->GCLK_PCHCTRL[TC4_GCLK_ID] =
		GCLK_PCHCTRL_WRTLOCK (0) |
		GCLK_PCHCTRL_GEN (3) | // 24MHZ
		GCLK_PCHCTRL_CHEN (1);

	TC4_REGS->COUNT8.TC_CTRLA = TC_CTRLA_SWRST (1);
	while (TC4_REGS->COUNT8.TC_SYNCBUSY & TC_SYNCBUSY_SWRST (1));

	TC4_REGS->COUNT8.TC_CTRLA =
		TC_CTRLA_COPEN1 (0) | TC_CTRLA_CAPTEN1 (0) |
		TC_CTRLA_COPEN0 (0) | TC_CTRLA_CAPTEN0 (0) |
		TC_CTRLA_ALOCK (0) |
		TC_CTRLA_PRESCALER_DIV1 |
		TC_CTRLA_ONDEMAND (0) |
		TC_CTRLA_RUNSTDBY (0) |
		TC_CTRLA_PRESCSYNC_GCLK |
		TC_CTRLA_MODE_COUNT8;
	TC4_REGS->COUNT8.TC_WAVE = TC_WAVE_WAVEGEN_NPWM;
	TC4_REGS->COUNT8.TC_DRVCTRL = TC_DRVCTRL_INVEN0 (0) | TC_DRVCTRL_INVEN1 (0);
	TC4_REGS->COUNT8.TC_PER = TC_COUNT8_PER_PER (99);
	TC4_REGS->COUNT8.TC_CC[0] = 0;

	TC4_REGS->COUNT8.TC_CTRLA |= TC_CTRLA_ENABLE (1);
}

void init_tc () {
	init_tc0_deadtime_counter ();
	init_tc4_fan_pwm ();
}
