#include <mtd_tcc.h>

/*
	TCC0 - BLDC PWM GEN.
	TCC1 - BLDC SW COMM./ INTERVAL CAPTURE
	TCC2 - RADIO PPM CAPTURE
*/
static void init_tcc0_mosfet_pwm () {
	MCLK_REGS->MCLK_APBCMASK |= MCLK_APBCMASK_TCC0 (1);

	GCLK_REGS->GCLK_PCHCTRL[TCC0_GCLK_ID] =
		GCLK_PCHCTRL_WRTLOCK (0) |
		GCLK_PCHCTRL_GEN (1) |
		GCLK_PCHCTRL_CHEN (1);
	
	TCC0_REGS->TCC_CTRLA = TCC_CTRLA_SWRST (1);
	while (TCC0_REGS->TCC_SYNCBUSY & TCC_SYNCBUSY_SWRST (1));

	TCC0_REGS->TCC_CTRLA =
		TCC_CTRLA_CPTEN3 (0) |
		TCC_CTRLA_CPTEN2 (0) |
		TCC_CTRLA_CPTEN1 (0) |
		TCC_CTRLA_CPTEN0 (0) |
		TCC_CTRLA_DMAOS (0) |
		TCC_CTRLA_MSYNC (0) |
		TCC_CTRLA_ALOCK (0) |
		TCC_CTRLA_PRESCSYNC_GCLK |
		TCC_CTRLA_RUNSTDBY (0) |
		TCC_CTRLA_PRESCALER_DIV1 |
		TCC_CTRLA_RESOLUTION_NONE;

	TCC0_REGS->TCC_CTRLBCLR = TCC_CTRLBCLR_DIR (1); // increase
	while (TCC0_REGS->TCC_SYNCBUSY & TCC_SYNCBUSY_CTRLB (1));

	TCC0_REGS->TCC_WAVE =
		TCC_WAVE_SWAP0 (0) | TCC_WAVE_SWAP1 (0) | TCC_WAVE_SWAP2 (0) | TCC_WAVE_SWAP3 (0) |
		TCC_WAVE_POL0 (0) | TCC_WAVE_POL1 (0) | TCC_WAVE_POL2 (0) | TCC_WAVE_POL3 (0) |
		TCC_WAVE_CICCEN0 (0) | TCC_WAVE_CICCEN1 (0) | TCC_WAVE_CICCEN2 (0) | TCC_WAVE_CICCEN3 (0) |
		TCC_WAVE_CIPEREN (0) |
		TCC_WAVE_RAMP_RAMP1 |
		TCC_WAVE_WAVEGEN_NPWM;
	while (TCC0_REGS->TCC_SYNCBUSY & TCC_SYNCBUSY_WAVE (1));
	
	TCC0_REGS->TCC_WEXCTRL =
		TCC_WEXCTRL_DTHS (0) | // deadtime high-side output value
		TCC_WEXCTRL_DTLS (0) | // deadtime low-side output value
		TCC_WEXCTRL_DTIEN0 (0) | TCC_WEXCTRL_DTIEN1 (0) | TCC_WEXCTRL_DTIEN2 (0) | TCC_WEXCTRL_DTIEN3 (0) |
		TCC_WEXCTRL_OTMX (1);
	TCC0_REGS->TCC_PATT = TCC_PATT_PGV (0x0) | TCC_PATT_PGE (0xFF);
	TCC0_REGS->TCC_PATTBUF = TCC_PATTBUF_PGVB (0) | TCC_PATTBUF_PGEB (0xFF);

	TCC0_REGS->TCC_PER = TCC_PER_PER (TCC0_PERIOD);
	TCC0_REGS->TCC_PERBUF = TCC_PERBUF_PERBUF (TCC0_PERIOD);
	TCC0_REGS->TCC_CC[0] = TCC_CC_CC (0); // high-side
	TCC0_REGS->TCC_CC[1] = TCC_CC_CC (0); // low-side

	TCC0_REGS->TCC_CTRLA |= TCC_CTRLA_ENABLE (1);
}

/*
	TCC1
	96MHz / 16 = 6MHz
	t = 1/6 uS
*/
static void init_tcc1 () {
	MCLK_REGS->MCLK_APBCMASK |= MCLK_APBCMASK_TCC1 (1);
	
	TCC1_REGS->TCC_CTRLA = TCC_CTRLA_SWRST (1);
	while (TCC1_REGS->TCC_SYNCBUSY & TCC_SYNCBUSY_SWRST (1));

	TCC1_REGS->TCC_CTRLA = 
		TCC_CTRLA_CPTEN3 (0) |
		TCC_CTRLA_CPTEN2 (0) |
		TCC_CTRLA_CPTEN1 (0) |
		TCC_CTRLA_CPTEN0 (0) |
		TCC_CTRLA_DMAOS (0) |
		TCC_CTRLA_MSYNC (0) |
		TCC_CTRLA_ALOCK (0) |
		TCC_CTRLA_PRESCSYNC_GCLK |
		TCC_CTRLA_RUNSTDBY (0) |
		TCC_CTRLA_PRESCALER_DIV16 |
		TCC_CTRLA_RESOLUTION_NONE;

	TCC1_REGS->TCC_CTRLBCLR = TCC_CTRLBCLR_DIR (1); // increase
	while (TCC1_REGS->TCC_SYNCBUSY & TCC_SYNCBUSY_CTRLB (1));

	TCC1_REGS->TCC_WAVE =
		TCC_WAVE_SWAP0 (0) | TCC_WAVE_SWAP1 (0) | TCC_WAVE_SWAP2 (0) | TCC_WAVE_SWAP3 (0) |
		TCC_WAVE_POL0 (0) | TCC_WAVE_POL1 (0) | TCC_WAVE_POL2 (0) | TCC_WAVE_POL3 (0) |
		TCC_WAVE_CICCEN0 (0) | TCC_WAVE_CICCEN1 (0) | TCC_WAVE_CICCEN2 (0) | TCC_WAVE_CICCEN3 (0) |
		TCC_WAVE_CIPEREN (0) |
		TCC_WAVE_RAMP_RAMP1 |
		TCC_WAVE_WAVEGEN_NPWM;
	while (TCC1_REGS->TCC_SYNCBUSY & TCC_SYNCBUSY_WAVE (1));
	
	TCC1_REGS->TCC_WEXCTRL =
		TCC_WEXCTRL_DTHS (0) |
		TCC_WEXCTRL_DTLS (0) |
		TCC_WEXCTRL_DTIEN0 (0) | TCC_WEXCTRL_DTIEN1 (0) | TCC_WEXCTRL_DTIEN2 (0) | TCC_WEXCTRL_DTIEN3 (0) |
		TCC_WEXCTRL_OTMX (1);
	TCC1_REGS->TCC_PATT = TCC_PATT_PGV (0x0) | TCC_PATT_PGE (0xFF);
	TCC1_REGS->TCC_PATTBUF = TCC_PATTBUF_PGVB (0) | TCC_PATTBUF_PGEB (0xFF);

	//TCC1_REGS->TCC_PER = TCC_PER_PER (1);
	//TCC1_REGS->TCC_PERBUF = TCC_PERBUF_PERBUF (1);
	//TCC1_REGS->TCC_CC[0] = TCC_CC_CC (0);
	//TCC1_REGS->TCC_CC[1] = TCC_CC_CC (0);

	TCC1_REGS->TCC_INTENSET = TCC_INTENSET_OVF (1);
}

static void init_tcc2_radio_capture () {
	MCLK_REGS->MCLK_APBCMASK |= MCLK_APBCMASK_TCC2 (1);

	GCLK_REGS->GCLK_PCHCTRL[TCC2_GCLK_ID] =
		GCLK_PCHCTRL_WRTLOCK (1) |
		GCLK_PCHCTRL_GEN (8) |
		GCLK_PCHCTRL_CHEN (1);

	TCC2_REGS->TCC_CTRLA = TCC_CTRLA_SWRST (1);
	while (TCC2_REGS->TCC_SYNCBUSY & TCC_SYNCBUSY_SWRST (1));

	TCC2_REGS->TCC_CTRLBCLR = TCC_CTRLBCLR_DIR (1); // increase
	TCC2_REGS->TCC_CTRLBSET = TCC_CTRLBSET_ONESHOT (1);
	TCC2_REGS->TCC_PERBUF = TCC_PERBUF_PERBUF (TCC2_PERIOD);
	TCC2_REGS->TCC_PER = TCC_PER_PER (TCC2_PERIOD);

	TCC2_REGS->TCC_EVCTRL = 
		TCC_EVCTRL_MCEO0 (0) |
		TCC_EVCTRL_MCEO1 (0) |
		TCC_EVCTRL_MCEO2 (0) |
		TCC_EVCTRL_MCEO3 (0) |
		TCC_EVCTRL_MCEI0 (1) |
		TCC_EVCTRL_MCEI1 (0) |
		TCC_EVCTRL_MCEI2 (0) |
		TCC_EVCTRL_MCEI3 (0) |
		TCC_EVCTRL_TCEI0 (1) |
		TCC_EVCTRL_TCEI1 (0) |
		TCC_EVCTRL_TCINV0 (0) |
		TCC_EVCTRL_TCINV1 (0) |
		TCC_EVCTRL_CNTEO (0) |
		TCC_EVCTRL_TRGEO (0) |
		TCC_EVCTRL_OVFEO (0) |
		TCC_EVCTRL_CNTSEL_START |
		TCC_EVCTRL_EVACT0_RETRIGGER |
		TCC_EVCTRL_EVACT1_OFF;

	TCC2_REGS->TCC_CTRLA =
		TCC_CTRLA_CPTEN0 (1) |
		TCC_CTRLA_CPTEN1 (0) |
		TCC_CTRLA_CPTEN2 (0) |
		TCC_CTRLA_CPTEN3 (0) |
		TCC_CTRLA_DMAOS (0) |
		TCC_CTRLA_MSYNC (0) |
		TCC_CTRLA_ALOCK (0) |
		TCC_CTRLA_PRESCSYNC_GCLK |
		TCC_CTRLA_RUNSTDBY (0) |
		TCC_CTRLA_PRESCALER_DIV8 |
		TCC_CTRLA_RESOLUTION_NONE |
		TCC_CTRLA_ENABLE (1);

	//while (TCC2_REGS->TCC_CTRLA & TCC_CTRLA_ENABLE (1) == 0);
}

void init_tcc () {
	init_tcc0_mosfet_pwm ();
	init_tcc1 ();
	init_tcc2_radio_capture ();
}
