#include <mtd_comp.h>

void init_comp () {
	MCLK_REGS->MCLK_APBCMASK |= MCLK_APBCMASK_AC (1);

	GCLK_REGS->GCLK_PCHCTRL[AC_GCLK_ID] =
		GCLK_PCHCTRL_WRTLOCK (0) |
		GCLK_PCHCTRL_GEN (0) |
		GCLK_PCHCTRL_CHEN (1);

	AC_REGS->AC_CTRLA = AC_CTRLA_SWRST (1);
	while (AC_REGS->AC_SYNCBUSY & AC_SYNCBUSY_SWRST (1));

	AC_REGS->AC_EVCTRL = // start comparator from event
		AC_EVCTRL_INVEI0 (0) |
		AC_EVCTRL_INVEI1 (0) |
		AC_EVCTRL_INVEI2 (0) |
		AC_EVCTRL_INVEI3 (0) |
		AC_EVCTRL_COMPEI0 (1) |
		AC_EVCTRL_COMPEI1 (1) |
		AC_EVCTRL_COMPEI2 (1) |
		AC_EVCTRL_COMPEI3 (0) |
		AC_EVCTRL_COMPEO0 (0) |
		AC_EVCTRL_COMPEI1 (0) |
		AC_EVCTRL_COMPEO2 (0) |
		AC_EVCTRL_COMPEO3 (0);

	AC_REGS->AC_INTENSET =
		AC_INTENSET_COMP0 (1) |
		AC_INTENSET_COMP1 (0) |
		AC_INTENSET_COMP2 (0) |
		AC_INTENSET_COMP3 (0);

	AC_REGS->AC_COMPCTRL[0] = 0; // C
	AC_REGS->AC_COMPCTRL[1] = 0; // B
	AC_REGS->AC_COMPCTRL[2] = 0; // A
	while (AC_REGS->AC_SYNCBUSY);

	AC_REGS->AC_CTRLA = AC_CTRLA_ENABLE (1);
	while (AC_REGS->AC_SYNCBUSY & AC_SYNCBUSY_ENABLE (1));

}
