#include <mtd_dmac.h>

#define DMA_CH_BLDC_HI_PWM 0
#define DMA_CH_BLDC_LO_PWM 1
#define DMA_CH_RADIO_PPM 2
#define DMA_CH_TSENS 11

void dmac_setup_channel (uint8_t id, uint32_t trig_src) {
	DMAC_REGS->DMAC_CHID = DMAC_CHID_ID (id);
	DMAC_REGS->DMAC_CHCTRLB =
		DMAC_CHCTRLB_EVACT_NOACT |
		DMAC_CHCTRLB_EVIE (0) |
		DMAC_CHCTRLB_EVOE (0) |
		DMAC_CHCTRLB_LVL_LVL0 |
		DMAC_CHCTRLB_TRIGSRC (trig_src) |
		DMAC_CHCTRLB_TRIGACT_BEAT;
	DMAC_REGS->DMAC_CHINTENSET = DMAC_CHINTENSET_TCMPL (1); // | DMAC_CHINTENSET_TERR (1);
	DMAC_REGS->DMAC_CHCTRLA = DMAC_CHCTRLA_ENABLE (1);

}

void init_dmac () {
	MCLK_REGS->MCLK_AHBMASK |= MCLK_AHBMASK_DMAC (1);
	MCLK_REGS->MCLK_APBBMASK |= MCLK_APBBMASK_HMATRIXHS (1);

	DMAC_REGS->DMAC_CTRL = DMAC_CTRL_SWRST (1);
	while (DMAC_REGS->DMAC_CTRL & DMAC_CTRL_SWRST (1));

	DMAC_REGS->DMAC_BASEADDR = DMAC_BASEADDR_BASEADDR ((uint32_t) DMA_DESCRIPTOR);
	DMAC_REGS->DMAC_WRBADDR  = DMAC_WRBADDR_WRBADDR   ((uint32_t) DMA_DESCRIPTOR_WB);

	// 設定通道
	DMA_DESCRIPTOR[0].DMAC_DSTADDR = DMAC_DSTADDR_DSTADDR ((uint32_t) &tsens_buf);
	dmac_setup_channel (0, DMAC_CHCTRLB_TRIGSRC_TSENS_Val);

	DMA_DESCRIPTOR[1].DMAC_DSTADDR = DMAC_DSTADDR_DSTADDR ((uint32_t) &mtd.input.radio_ppm);
	dmac_setup_channel (1, DMAC_CHCTRLB_TRIGSRC_TCC2_MC0_Val);

	if (DSU_REGS->DSU_STATUSB & DSU_STATUSB_DBGPRES (1)) {
		DMAC_REGS->DMAC_DBGCTRL = DMAC_DBGCTRL_DBGRUN (1);
	}

	DMAC_REGS->DMAC_CTRL =
		DMAC_CTRL_LVLEN0 (1) |
		DMAC_CTRL_LVLEN1 (0) |
		DMAC_CTRL_LVLEN2 (0) |
		DMAC_CTRL_LVLEN3 (0) |
		DMAC_CTRL_DMAENABLE (1);
}

void DMAC_Handler () {
	uint8_t ch_curr = 0;

	//for (ch_curr = 0; ch_curr < DMAC_CH_NUM; ch_curr ++) {
	//if (DMAC_REGS->DMAC_INTSTATUS & DMAC_INTSTATUS_CHINT (ch_curr)) {
	if (DMAC_REGS->DMAC_INTSTATUS & DMAC_INTSTATUS_CHINT1 (1)) {
	
		DMAC_REGS->DMAC_CHID = DMAC_CHID_ID (1);

		if (DMAC_REGS->DMAC_CHINTFLAG & DMAC_CHINTFLAG_TERR (1)) {

		}

		if (DMAC_REGS->DMAC_CHINTFLAG & DMAC_CHINTFLAG_TCMPL (1)) {
			DMAC_REGS->DMAC_CHCTRLB |= DMAC_CHCTRLB_CMD_RESUME;
			DMAC_REGS->DMAC_CHCTRLA = DMAC_CHCTRLA_ENABLE (1);
		}

		if (DMAC_REGS->DMAC_CHINTFLAG & DMAC_CHINTFLAG_SUSP (1)) {
			DMAC_REGS->DMAC_CHCTRLB |= DMAC_CHCTRLB_CMD_RESUME;
		}

		DMAC_REGS->DMAC_CHINTFLAG = DMAC_CHINTFLAG_TERR (1) | DMAC_CHINTFLAG_TCMPL (1) | DMAC_CHINTENCLR_SUSP (1);
	}
	//}
}
