#include <bldc.h>

/*
	[DIR][STEP]
	DIR 0 CW
	DIR 1 CCW
*/
const uint16_t BLDC_NEXT_STEP_TABLE[2][6] = {
	{1, 2, 3, 4, 5, 0},
	{5, 0, 1, 2, 3, 4}
};

/*
	AH - TCC0/W6 - BIT6
	AL - TCC0/W7 - BIT7
	BH - TCC0/W2 - BIT2
	BL - TCC0/W3 - BIT3
	CH - TCC0/W4 - BIT4
	CL - TCC0/W5 - BIT5

	PGV為PGE=1時套用輸出準位
	V=0 E=1時被mask住 輸出V=0
	V=x E=0時不被mask住 輸出CC[n]PWM
*/
const uint16_t BLDC_PATT_VALUE_TABLE[6] = {
	0x00B7, //AB
	0x009F, //AC
	0x00DB, //BC
	0x007B, //BA
	0x006F, //CA
	0x00E7  //CB
};

/*
*/
const uint32_t BLDC_COMPARATOR_USING_TABLE[6] = {
	0, 1, 2, 0, 1, 2
};

/*
*/
const uint32_t BLDC_COMPARATOR_SETUP_TABLE[2][6] = {
	{ // CW
		// STEP0 - C-FALLING	
		AC_COMPCTRL_OUT_OFF |
		AC_COMPCTRL_FLEN_MAJ5 |
		AC_COMPCTRL_HYSTEN (1) |
		AC_COMPCTRL_SPEED_HIGH |
		AC_COMPCTRL_SWAP (0) |
		AC_COMPCTRL_MUXPOS_PIN0 | // BEMF-C (PA04)
		AC_COMPCTRL_MUXNEG_PIN3 | // NEUTRO (PA07)
		AC_COMPCTRL_RUNSTDBY (0) |
		AC_COMPCTRL_INTSEL_FALLING |
		AC_COMPCTRL_SINGLE (0) |
		AC_COMPCTRL_ENABLE (1),

		// STEP1 - B-RISING	
		AC_COMPCTRL_OUT_OFF |
		AC_COMPCTRL_FLEN_MAJ5 |
		AC_COMPCTRL_HYSTEN (1) |
		AC_COMPCTRL_SPEED_HIGH |
		AC_COMPCTRL_SWAP (0) |
		AC_COMPCTRL_MUXPOS_PIN1 | // BEMF-B (PA04)
		AC_COMPCTRL_MUXNEG_PIN3 | // NEUTRO (PA07)
		AC_COMPCTRL_RUNSTDBY (0) |
		AC_COMPCTRL_INTSEL_RISING |
		AC_COMPCTRL_SINGLE (0) |
		AC_COMPCTRL_ENABLE (1),
		
		// STEP2 - A-FALLING	
		AC_COMPCTRL_OUT_OFF |
		AC_COMPCTRL_FLEN_MAJ5 |
		AC_COMPCTRL_HYSTEN (1) |
		AC_COMPCTRL_SPEED_HIGH |
		AC_COMPCTRL_SWAP (0) |
		AC_COMPCTRL_MUXPOS_PIN2 | // BEMF-B (PA04)
		AC_COMPCTRL_MUXNEG_PIN3 | // NEUTRO (PA07)
		AC_COMPCTRL_RUNSTDBY (0) |
		AC_COMPCTRL_INTSEL_FALLING |
		AC_COMPCTRL_SINGLE (0) |
		AC_COMPCTRL_ENABLE (1),
		
		// STEP3 - C-RISING	
		AC_COMPCTRL_OUT_OFF |
		AC_COMPCTRL_FLEN_MAJ5 |
		AC_COMPCTRL_HYSTEN (1) |
		AC_COMPCTRL_SPEED_HIGH |
		AC_COMPCTRL_SWAP (0) |
		AC_COMPCTRL_MUXPOS_PIN0 | // BEMF-C (PA04)
		AC_COMPCTRL_MUXNEG_PIN3 | // NEUTRO (PA07)
		AC_COMPCTRL_RUNSTDBY (0) |
		AC_COMPCTRL_INTSEL_RISING |
		AC_COMPCTRL_SINGLE (0) |
		AC_COMPCTRL_ENABLE (1),

		// STEP4 - B-FALLING	
		AC_COMPCTRL_OUT_OFF |
		AC_COMPCTRL_FLEN_MAJ5 |
		AC_COMPCTRL_HYSTEN (1) |
		AC_COMPCTRL_SPEED_HIGH |
		AC_COMPCTRL_SWAP (0) |
		AC_COMPCTRL_MUXPOS_PIN1 | // BEMF-B (PA04)
		AC_COMPCTRL_MUXNEG_PIN3 | // NEUTRO (PA07)
		AC_COMPCTRL_RUNSTDBY (0) |
		AC_COMPCTRL_INTSEL_FALLING |
		AC_COMPCTRL_SINGLE (0) |
		AC_COMPCTRL_ENABLE (1),
		
		// STEP5 - A-RISING	
		AC_COMPCTRL_OUT_OFF |
		AC_COMPCTRL_FLEN_MAJ5 |
		AC_COMPCTRL_HYSTEN (1) |
		AC_COMPCTRL_SPEED_HIGH |
		AC_COMPCTRL_SWAP (0) |
		AC_COMPCTRL_MUXPOS_PIN2 | // BEMF-B (PA04)
		AC_COMPCTRL_MUXNEG_PIN3 | // NEUTRO (PA07)
		AC_COMPCTRL_RUNSTDBY (0) |
		AC_COMPCTRL_INTSEL_RISING |
		AC_COMPCTRL_SINGLE (0) |
		AC_COMPCTRL_ENABLE (1),
	},
	{ // CCW
	}
};
